Config = Config or {}

Config.Cardealer = {
    OrderDeliveryTime = 60 * 60,

    Categories = {
        { name = "Compatte",    id = 1 },
        { name = "Muscle",      id = 2 },
        { name = "Berline",     id = 3 },
        { name = "Fuoristrada", id = 4 },
        { name = "Furgoni",     id = 5 },
        { name = "Sportive",    id = 6 },
        { name = "Moto",        id = 7 },
    },

    Vehicles = {
        { name = "rhapsody",   price = 4369,   category = 1 },
        { name = "weevil",     price = 2849,   category = 1 },
        { name = "dynasty",    price = 3324,   category = 1 },
        { name = "retinue",    price = 7219,   category = 1 },
        { name = "savestra",   price = 6839,   category = 1 },
        { name = "michelli",   price = 6650,   category = 1 },
        { name = "zinger",     price = 3514,   category = 1 },
        { name = "fagaloa",    price = 3039,   category = 1 },
        { name = "clique3",    price = 3419,   category = 1 },
        { name = "issi3",      price = 4513,   category = 1 },

        { name = "emperor",    price = 3134,   category = 3 },
        { name = "regina",     price = 2803,   category = 3 },
        { name = "greenwood2", price = 4418,   category = 3 },
        { name = "gwoods",     price = 4559,   category = 3 },
        { name = "panorama",   price = 2850,   category = 3 },
        { name = "regina4",    price = 3134,   category = 3 },
        { name = "brigham",    price = 2944,   category = 3 },
        { name = "clique2",    price = 2754,   category = 3 },
        { name = "eudora",     price = 3753,   category = 3 },
        { name = "greenwood",  price = 4939,   category = 3 },
        { name = "impaler6",   price = 5984,   category = 3 },
        { name = "tahoma",     price = 5843,   category = 3 },
        { name = "tulip2",     price = 8739,   category = 3 },
        { name = "virgo2",     price = 4749,   category = 3 },
        { name = "voodoo4",    price = 4084,   category = 3 },
        { name = "starlett",   price = 3324,   category = 3 },
        { name = "fagaloac",   price = 3943,   category = 3 },
        { name = "manana",     price = 3419,   category = 3 },
        { name = "peyote",     price = 4513,   category = 3 },
        { name = "tornado",    price = 4749,   category = 3 },
        { name = "voodooc",    price = 7599,   category = 3 },

        { name = "buccaneer",  price = 9499,   category = 2 },
        { name = "chino",      price = 4513,   category = 2 },
        { name = "deviant",    price = 17338,  category = 2 },
        { name = "dominator8", price = 18003,  category = 2 },
        { name = "dukes",      price = 13489,  category = 2 },
        { name = "ellie",      price = 16388,  category = 2 },
        { name = "gauntlet3",  price = 11114,  category = 2 },
        { name = "gauntlet5",  price = 12064,  category = 2 },
        { name = "impaler",    price = 11353,  category = 2 },
        { name = "sabregt",    price = 13253,  category = 2 },
        { name = "stalion",    price = 11779,  category = 2 },
        { name = "tampa",      price = 10498,  category = 2 },
        { name = "tulip",      price = 12349,  category = 2 },
        { name = "vamos",      price = 9643,   category = 2 },
        { name = "virgo",      price = 9453,   category = 2 },
        { name = "phoenix",    price = 13443,  category = 2 },
        { name = "domc",       price = 18239,  category = 2 },
        { name = "gauntletc",  price = 16149,  category = 2 },
        { name = "paradox",    price = 12824,  category = 2 },
        { name = "vulture",    price = 17099,  category = 2 },
        { name = "rapidgt3",   price = 17053,  category = 2 },

        { name = "casco",      price = 29639,  category = 6 },
        { name = "coquette2",  price = 48734,  category = 6 },
        { name = "coquette5",  price = 48069,  category = 6 },
        { name = "feltzer3",   price = 57189,  category = 6 },
        { name = "gt500",      price = 53199,  category = 6 },
        { name = "mamba",      price = 61228,  category = 6 },
        { name = "monroe",     price = 94999,  category = 6 },
        { name = "stinger",    price = 34153,  category = 6 },
        { name = "swinger",    price = 78803,  category = 6 },
        { name = "torero",     price = 118750, category = 6 },
        { name = "viseris",    price = 104500, category = 6 },
        { name = "z190",       price = 34104,  category = 6 },
        { name = "pigalle",    price = 25269,  category = 6 },
        { name = "elena",      price = 60088,  category = 6 },
        { name = "euphoria",   price = 28974,  category = 6 },
        { name = "lynxmk1",    price = 59089,  category = 6 },
        { name = "sancyb4",    price = 28499,  category = 6 },
        { name = "cavallos2",  price = 142500, category = 6 },
        { name = "coquette3",  price = 50398,  category = 6 },
        { name = "hermes",     price = 78469,  category = 6 },
        { name = "broadway",   price = 10445,  category = 6 },

        { name = "avarus",     price = 12588,  category = 7 },
        { name = "daemon2",    price = 11399,  category = 7 },
        { name = "wolfsbane",  price = 9214,   category = 7 },
        { name = "zombieb",    price = 7504,   category = 7 },
        { name = "zombiea",    price = 8123,   category = 7 },
        { name = "hexer",      price = 9453,   category = 7 },

        { name = "rancherxl",  price = 4844,   category = 4 },
        { name = "rebel2",     price = 6603,   category = 4 },
        { name = "yosemite3",  price = 6602,   category = 4 },

        { name = "slamvan",    price = 6033,   category = 5 },
        { name = "picador",    price = 9073,   category = 5 },
        { name = "ratloader3", price = 5984,   category = 5 },
        { name = "surfer3",    price = 6793,   category = 5 },
        { name = "journey2",   price = 14203,  category = 5 },
        { name = "youga2",     price = 5938,   category = 5 },
    }

}
